### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/David-Melero-Formularo-Bootstrap#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen proyecto @dmeleroandrade  ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Intenta modificarlo para que se parezca al [original](https://storage.googleapis.com/breathecode-asset-images/b1dce6958cdd29b72248a6db2e6450994eedbaeae3f9086b5bc78a30cfa2d15c.png?raw=true) en estos puntos.
![Captura de pantalla de 2024-03-14 11-25-46](https://github.com/4GeeksAcademy/David-Melero-Formularo-Bootstrap/assets/139759297/8f3600fd-b2b9-4312-bc2e-4419bbd364bd)
![Captura de pantalla de 2024-03-14 11-25-55](https://github.com/4GeeksAcademy/David-Melero-Formularo-Bootstrap/assets/139759297/ed38cb48-61f4-470b-bb05-5e21e98e47f1)
"Payment form example" no es un `<p>`
<br>
<br>
<br>

![Captura de pantalla de 2024-03-14 11-27-54](https://github.com/4GeeksAcademy/David-Melero-Formularo-Bootstrap/assets/139759297/6c6e8960-b933-4c61-8c18-ecfb37273ace)
![Captura de pantalla de 2024-03-14 11-27-59](https://github.com/4GeeksAcademy/David-Melero-Formularo-Bootstrap/assets/139759297/65c64972-b310-453e-91f4-6b0ebe6a014b)
Te falta un elemento
<br>
<br>
<br>

![Captura de pantalla de 2024-03-14 11-30-47](https://github.com/4GeeksAcademy/David-Melero-Formularo-Bootstrap/assets/139759297/8ec9811c-4006-4c51-9e75-b5701260c47b)
![Captura de pantalla de 2024-03-14 11-30-55](https://github.com/4GeeksAcademy/David-Melero-Formularo-Bootstrap/assets/139759297/5f7f4da9-e746-4be7-baba-f7ae2ccf7ae3)
El original no tiene ese gris

**Comment by dmeleroandrade** [comment]
Muchas gracias Edo.

Mejoraré los aspectos que me has dicho. 

* No supe ajustar el header y footer a los márgenes..

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo @dmeleroandrade :clap::clap::clap:
